"""
Sample usage examples for GPT Doc Reader.
"""

from gpt_doc_reader import DocumentReader, MarkdownConverter, DocumentStorage
from gpt_doc_reader.utils import get_statistics


def example_1_basic_usage():
    """Example 1: Basic document loading and conversion."""
    print("=" * 50)
    print("Example 1: Basic Usage")
    print("=" * 50)
    
    reader = DocumentReader()
    
    # Load from text
    text_content = """# My ChatGPT Document

This is a sample document generated by ChatGPT.

## Section 1
Some content here.

## Section 2
More content here.
"""
    
    doc = reader.load_from_text(text_content, "sample.txt")
    print(f"Loaded: {doc}")
    print(f"Content length: {len(doc.content)} characters\n")


def example_2_conversion():
    """Example 2: Convert document to different formats."""
    print("=" * 50)
    print("Example 2: Format Conversion")
    print("=" * 50)
    
    reader = DocumentReader()
    
    text_content = """# Project Report

## Overview
This is a comprehensive project report.

## Results
- Point 1
- Point 2
- Point 3
"""
    
    doc = reader.load_from_text(text_content, "report.txt")
    
    # Convert to markdown
    converter = MarkdownConverter()
    markdown = converter.convert(doc)
    print("Converted to Markdown:")
    print(markdown)
    print()


def example_3_sections():
    """Example 3: Extract sections from document."""
    print("=" * 50)
    print("Example 3: Extract Sections")
    print("=" * 50)
    
    reader = DocumentReader()
    
    text_content = """# Main Title

## Introduction
Introduction content here.

## Main Content
Main content here.

## Conclusion
Conclusion content here.
"""
    
    doc = reader.load_from_text(text_content, "article.txt")
    sections = reader.extract_sections(doc)
    
    print("Extracted sections:")
    for section_name, section_content in sections.items():
        print(f"\n[{section_name}]")
        print(section_content[:100] + "..." if len(section_content) > 100 else section_content)


def example_4_statistics():
    """Example 4: Get document statistics."""
    print("=" * 50)
    print("Example 4: Document Statistics")
    print("=" * 50)
    
    reader = DocumentReader()
    
    text_content = """# My Document

This is a sample document. It contains several sentences. Each sentence provides information.

Another paragraph starts here. This paragraph has more content. The content is meaningful.
"""
    
    doc = reader.load_from_text(text_content, "stats.txt")
    stats = get_statistics(doc.content)
    
    print("Document Statistics:")
    for key, value in stats.items():
        print(f"  {key}: {value}")
    print()


def example_5_storage():
    """Example 5: Save and manage documents."""
    print("=" * 50)
    print("Example 5: Storage Management")
    print("=" * 50)
    
    storage = DocumentStorage(storage_path="./sample_documents")
    
    # Create a sample document
    from gpt_doc_reader import Document
    doc = Document(
        content="This is a stored document.",
        filename="stored_doc"
    )
    
    # Save it
    saved_path = storage.save_document(doc, output_format="md")
    print(f"Document saved to: {saved_path}")
    
    # Get storage stats
    stats = storage.get_storage_stats()
    print(f"\nStorage Stats:")
    print(f"  Files: {stats['file_count']}")
    print(f"  Total size: {stats['total_size_mb']} MB")
    print()


def example_6_cleanup():
    """Example 6: Clean document content."""
    print("=" * 50)
    print("Example 6: Content Cleanup")
    print("=" * 50)
    
    reader = DocumentReader()
    
    # Document with messy formatting
    messy_content = """# Document Title

First paragraph.


Second paragraph after multiple blank lines.



Third paragraph.
"""
    
    doc = reader.load_from_text(messy_content, "messy.txt")
    cleaned = reader.clean_content(doc)
    
    print("Original:")
    print(repr(messy_content))
    print("\nCleaned:")
    print(repr(cleaned))
    print()


if __name__ == "__main__":
    example_1_basic_usage()
    example_2_conversion()
    example_3_sections()
    example_4_statistics()
    example_5_storage()
    example_6_cleanup()
    
    print("=" * 50)
    print("All examples completed!")
    print("=" * 50)